### ISSUE TITLE
hadolintの導入

### ISSUE THREAD

**Issue by yamap55** [yamazaki-seiya/homeru_kun#18]
Dockerfileのlinterであるhadolintを導入を検討する

## 詳細
- Dockerfileの専門家ではないため正しく記載するのが難しい
- コンテナはセキュリティリスクが高いため静的解析ツールでチェックをしたい

## メモ
- 導入自体は私の個人リポジトリの内容がそのまま使用できるかと思われる
  - [Dockerへの導入](https://github.com/yamap55/python_repository_simple/blob/master/.devcontainer/Dockerfile#L53..L54)
  - [設定ファイル](https://github.com/yamap55/python_repository_simple/blob/master/.hadolint.yaml)
  - [GitHub Actions](https://github.com/yamap55/python_repository_simple/blob/master/.github/workflows/hadolint.yml)

## 参考
- 公式サイト
  - https://github.com/hadolint/hadolint

**Comment by yamazaki-seiya** [comment]
これやっちゃっていいと思うので、私導入しますね。
