### ISSUE TITLE
PRのテンプレ導入

### ISSUE THREAD

**Issue by yamazaki-seiya** [yamazaki-seiya/homeru_kun#20]
### 概要
- PRのテンプレを導入したい

### 理由
1. 何の機能を実装したか、どんな修正をしたかなどが読みやすいから
2. PR出す側も何をすれば良いか明確になり、何をしたのか整理されるから

**Comment by yamap55** [comment]
書くのが手間にならない（面倒にならない）位のシンプルな感じが良いかと思います。
それこそこのIssueのような感じで↓位で導入し、もう少し情報欲しいとか、レビュー時に情報足りないとかあったら足す感じでどうでしょうか。（大きいPJだとチェックリストあったりしますが。）

```
## 概要

- a

## 詳細

- a

```

**Comment by yamazaki-seiya** [comment]
↑良いと思います！
やりますね。
