### ISSUE TITLE
mainをprotectedブランチにする

### ISSUE THREAD

**Issue by yamap55** [yamazaki-seiya/homeru_kun#23]
mainに直接pushする事を防ぐため、mainをprotectedブランチにした方が良いと思われる。
既に事象が発生してしまっている。（ https://github.com/yamazaki-seiya/homeru_kun/commit/578e3967341327e46dc10197067dccbf58e36d7c ）

## 参考
https://docs.github.com/ja/github/administering-a-repository/about-protected-branches

**Comment by yamazaki-seiya** [comment]
ありがとうございます。
上記対応しました！
