### ISSUE TITLE
6人以上メンションされた場合に、ほめる言葉リストの要素不足エラーが発生することの対応

### ISSUE THREAD

**Issue by Ayana2020** [yamazaki-seiya/homeru_kun#28]

**Comment by yamap55** [comment]
現コメント記載時点で、褒める言葉が5個定義されており、複数回褒める場合にListからpop処理を使うことで褒め言葉が重複しないようにしている。
そのため、規定された褒め言葉以上を褒めようとすると例外が発生すると思われる。

## 具体例
5個褒め言葉が規定されていた場合に、以下の発言を行うなど。

```
@user1 @user2 @user3 @user4 @user5 @user6 みんなのおかげでうまくいきました！
```


## 対応案
- 重複を許容する
- 事実上問題ない程度まで言葉を定義する
  - 複数の言葉、絵文字を組み合わせる事で数を増やせるので、一見重複していないように見せることも可能ではないか。
  - そもそも、複数人を指定することが稀であると思われるため。

**Comment by yamap55** [comment]
#24 内で対応済みのためClose
