### ISSUE TITLE
開発環境のpythonバージョンを3.9.5に指定

### ISSUE THREAD

**Issue by yamazaki-seiya** [yamazaki-seiya/homeru_kun#48]
## 概要
- 現状
  - 実行環境と開発環境でpythonのバージョンが異なる 
      - 実行環境 3.9.5
      - 開発環境 3.8.2
- 理想
  - 開発環境のバージョンを3.9.5に固定
- 対応方法
  - 以下3ファイルのpythonバージョンを指定している部分を修正
    - pyrightconfig.json
    - README.md
    - Dickerfile

**Comment by yamap55** [comment]
## 関連
- https://github.com/yamazaki-seiya/homeru_kun/pull/22?w=1#discussion_r630388814
- https://devcenter.heroku.com/articles/python-runtimes
  - ※日本語にすると記載がかなり古いので注意
- https://devcenter.heroku.com/articles/python-support
  - ※日本語にすると記載がかなり古いので注意
